### ISSUE TITLE
[ic-side-navigation]: Review component in relation to PR checklist

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#1132]
## Summary 
A revised checklist has been added to the PR summary which lists actions to be performed on any updates to a component. This ticket is to review the list and apply any updates to side navigation that are required.

## 💬 Description 
Review side navigation in relation to new PR checklist to prep for further updates. For current components, this approach may be useful as it will streamline any new PRs and keep any ticketed updates in scope:
 
Full list of PR checks:
- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] All acceptance criteria reviewed and met. 
- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge).
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [ ] All prop combinations work without issue. 

## 💰 Use value 
This preps the side navigation for any further work without the work falling out of scope due to a high number of changes related to the PR checklist. 

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.  

*Given as a developer working on the side navigation component* 
*When I create a PR with bug fixes and updates*  
*Then the ticket will stay in scope and not contain more updates relevant to the PR checklist* 

## ✏ Designs 
N/A

## 🧾 Guidance 
N/A

## Additional info 
Tell us anything else useful to help us understand your suggestion.

**Comment by MI6-255** [comment]
Do we have an issue for every component?

**Comment by MI6-255** [comment]
Create an epic for this

**Comment by GCHQ-Developer-530** [comment]
Done as part of epic #1817
