### ISSUE TITLE
Review each component against the PR checklist

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#1817]
## Summary 
Review each component against the PR checklist - [CHECKLIST.md](https://github.com/mi6/ic-ui-kit/blob/main/CHECKLIST.md)

## 💬 Description 
In preparation for v3 and to fix any tech debt, we need to review every component against the PR checklist. This issue reviews and fixes any issues that occur from it not passing each check. The following components need to go through the check:
- [x] Accordion @GCHQ-Developer-530 (Issue #1856 raised)
- [x] Alert @GCHQ-Developer-530 
- [x] Back to top - all good except for a11y issue: #1846
- [x] Badge @GCHQ-Developer-741 #1798, #1796, #1797 
- [x] Breadcrumb @GCHQ-Developer-299 
- [x] Button @GCHQ-Developer-299 #1898 
- [x] Card @GCHQ-Developer-530 (#1860 and #1861 raised)
- [x] Checkbox @GCHQ-Developer-741 #1647, #1586, #1803 
- [x] Chip @GCHQ-Developer-741  
- [x] Classification banner @GCHQ-Developer-465 
- [x] Data entity @GCHQ-Developer-530 
- [x] Dialog @GCHQ-Developer-530 
- [x] Empty state @GCHQ-Developer-465  (https://github.com/mi6/ic-ui-kit/issues/1592)
- [x] Footer @GCHQ-Developer-530 (#1869 raised + #1686)
- [x] Hero @GCHQ-Developer-530 (#1883 and #1884 raised)
- [x] Link @GCHQ-Developer-299 
- [x] Loading indicator @GCHQ-Developer-530 
- [x] Page header @GCHQ-Developer-530 (#1908, #1909 and #1910 raised)
- [x] Pagination @ad9242 #1808 #1871 
- [x] Popover menu @GCHQ-Developer-741 #1601 #1736 (#1897 #1900 raised from this work)
- [x] Radio button @GCHQ-Developer-741 #1804 #1602 #1820 #1794 
- [x] Search bar @GCHQ-Developer-530 #1891 (#1911, #1912 and #1913 raised)
- [x] Section container @GCHQ-Developer-465
- [x] Select @GCHQ-Developer-741 #1604 
- [x] Side navigation @GCHQ-Developer-530 #1132 (#1920, #1921, #1922, #1923 raised)
- [x] Skeleton @GCHQ-Developer-741 
- [x] Status tag @GCHQ-Developer-465 https://github.com/mi6/ic-ui-kit/issues/239 https://github.com/mi6/ic-ui-kit/issues/1608 #1891
- [x] Stepper @GCHQ-Developer-530 (#1907, #1914 raised)
- [x] Switch @GCHQ-Developer-299  https://github.com/mi6/ic-ui-kit/issues/960 #1891
- [x] Tabs @GCHQ-Developer-299 
- [x] Text field @ad9242 #1876 , #1769 
- [x] Toast @GCHQ-Developer-299 Accessibility issues: #1291  https://github.com/mi6/ic-ui-kit/issues/1926
- [x] Toggle button @gd2910 #1893 
- [x] Tooltip @GCHQ-Developer-530 #1891 (#1915, #1916 raised)
- [x] Top navigation @GCHQ-Developer-741 #1244 #1619 https://github.com/mi6/ic-design-system/issues/910 #1633 #1873
- [x] Typography @GCHQ-Developer-530 (Issues #1854 and #1855 raised)

## 💰 User value 
Ensure ICDS and our customers can assure the quality of the components.

**Comment by MI6-255** [comment]
Consider which have been accessibility tested already with @GCHQ-Developer-299

**Comment by GCHQ-Developer-530** [comment]
To avoid conflicts, if there are any changes to be made to a component then a new branch should be made per component (or couple of components if there's hardly any changes) off develop.
