### ISSUE TITLE
Replace remaining e2e tests with Cypress

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#2097]
## Summary 
There are still some components with puppeteer e2e tests which need replacing. Affects the following components

- [x] ic-navigation-menu #2698 
- [x] ic-radio-group #1794
- [x] ic-search-bar #2016
- [x] ic-status-tag #2052
- [x] ic-stepper #2051
- [x] ic-switch #2078 
- [ ] ic-theme - suggest this is only done in v3 code base due to a number of changes to component - additional tests will be required for new `theme` prop
- [x] ic-tooltip #2089
- [x] ic-typography

Tests should cover at least the functionality that exists in the e2e tests & improve\expand if necessary. The e2e test files should be removed as part of the work
