### ISSUE TITLE
Dark Mode: Component Tokens 

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-ui-kit#2289]
## Summary 
Go through the Figma file and create the Component Tokens. This is progression from the Semantic Tokens. 
(NOTE: Button has been started)

## 💬 Description 
In preparation for dark mode and to fix inconsistencies, we need to review every component and create the naming conventions in Figma via the local variables. 

**NOTE: When working on a component, please assign yourselves with "@" against a component. Once complete please tick the component off and move onto the next one and note down below that it is 'READY TO REVIEW' in the peer review section. Please refer to this [ticket](https://github.com/mi6/ic-ui-kit/issues/2241) for an example of this layout.**

Assigned people :
- [x] Accordion @GCHQDeveloper618 
- [x] Alert @GCHQDeveloper823 - (work done) [Dependency=Button]
- [x] Atoms @GCHQDeveloper823 
- [x] Back to top @GCHQDeveloper618 
- [x] Badge @GCHQ-Developer-465 
- [x] Breadcrumb @GCHQDeveloper823 [Dependency=Link]
- [x] Button @GCHQ-Developer-701 
- [x] Card horizontal @GCHQ-Developer-701 [Dependency=Button, Checkbox, Status Tag]
- [x] Card vertical @GCHQ-Developer-701 [Dependency=Button, Checkbox, Status Tag]
- [x] Checkbox @GCHQDeveloper823 [Dependency=Text Field]
- [x] Chip @mi6-577  
- [x] Classification Banner @mi6-577  
- [x] Data entity @mi6-577 [Dependency=Link]
- [x] Data table @GCHQDeveloper823 
- [x] Date picker [Dependency=Text Field, button] @mi6-577
- [x] Dialog @GCHQ-Developer-701 [Dependency=Alert, Button, Checkbox, Radio Button, Select, Switch]
- [x] Divider  @GCHQ-Developer-465 
- [x] Drawer @GCHQDeveloper618 
- [x] Empty state @GCHQ-Developer-465 [Dependency=Button, Link]
- [x] Footer @GCHQ-Developer-465 [Dependency=Accordion, Classification Banner, Link]
- [x] Hero @GCHQ-Developer-465 (work done) [Dependency=Button, Link, Search Bar, Text Field] 
- [x] Link @GCHQDeveloper823
- [x] Loading indicator @GCHQDeveloper823 - see comments on file
- [x] Navigation bar @GCHQ-Developer-465 [Dependency=Link]
- [x] Page header @GCHQ-Developer-701  [Dependency=Breadcrumb, Button, Chip, Search Bar, Stepper, Tabs, Text Field]
- [x] Pagination @GCHQ-Developer-465 [Dependency=Button, Select, Text Field]
- [x] Popover menu @mi6-577 
- [x] Radio button @mi6-577 [Dependency=Text Field]
- [x] Search bar @GCHQDeveloper618 
- [x] Select @GCHQDeveloper823 [Dependency=Button]
- [x] Side navigation @GCHQ-Developer-465 - waiting on comments from others :) [Dependency=Button]
- [x] Skeleton @GCHQ-Developer-465 
- [x] Status tag @GCHQ-Developer-465 
- [x] Stepper @GCHQDeveloper618 - related [ticket](https://github.com/mi6/ic-ui-kit/issues/2050)
- [x] Switch @mi6-577 - related [ticket](https://github.com/mi6/ic-ui-kit/issues/960) 
- [x] Tabs @GCHQDeveloper618  [Dependency=Button]
- [x] Table of content @GCHQ-Developer-465 
- [x] Text field @GCHQDeveloper823 
- [x] Toast @GCHQDeveloper823 - see comments on file - (work done) [Dependency=Button, Link]
- [x] Toggle button - @GCHQ-Developer-701 related [ticket](https://github.com/mi6/ic-ui-kit/issues/2018)
- [x] Tooltip @GCHQDeveloper618 
- [x] Top navigation  @GCHQ-Developer-465 [Dependency=Button, Link, Search Bar]
- [x] Tree view @GCHQDeveloper618

**NOTE: When reviewing a component, please assign yourselves with "@" against a component. Minimum of 2 reviewers are needed. Once complete please tick the component off and move onto the next one. Please refer to this [ticket](https://github.com/mi6/ic-ui-kit/issues/2241) for an example of this layout. Once it has been ticked then the component is ready for dev.**

Peer reviewed:

- [x] Accordion **READY TO DEV** @mi6-577  @GCHQ-Developer-094 @GCHQDeveloper823
- [x] Alert **READY TO DEV** (see comments on file) @GCHQ-Developer-465
- [x] Atoms **READY TO DEV** @GCHQ-Developer-701 - added 💬  @GCHQ-Developer-465 @GCHQDeveloper823 
- [x] Back to top **READY TO DEV** @GCHQ-Developer-465  @GCHQ-Developer-701 
- [x] Badge  **READY TO DEV** @mi6-577 @GCHQDeveloper823 @GCHQ-Developer-701
- [x] Breadcrumb **READY TO DEV** @GCHQ-Developer-701 @mi6-577  @GCHQ-Developer-094
- [x] Button **READY TO DEV** @mi6-577 @GCHQ-Developer-094 @GCHQ-Developer-465 
- [x] Card horizontal **READY TO DEV** @mi6-577 
- [x] Card vertical **READY TO DEV** @GCHQ-Developer-465 @mi6-577 
- [x] Checkbox **READY TO DEV** @GCHQDeveloper618 @GCHQ-Developer-701
- [X] Chip **READY TO DEV** @GCHQ-Developer-701, @GCHQ-Developer-465 
- [x] Classification Banner **READY TO DEV** @GCHQDeveloper823 
- [X] Data entity **READY TO DEV** @GCHQDeveloper823, @GCHQ-Developer-465 @GCHQDeveloper618 
- [x] Date picker **READY TO DEV** @GCHQDeveloper618 @GCHQ-Developer-465 @GCHQDeveloper823 
- [X] Dialog **READY TO DEV** @GCHQ-Developer-465 @GCHQDeveloper823
- [x] Data table **READY TO DEV** @GCHQ-Developer-701 
- [x] Divider  **READY TO DEV** @GCHQ-Developer-701 @GCHQDeveloper823
- [x] Drawer **READY TO DEV** @GCHQ-Developer-465 @GCHQ-Developer-701
- [x] Empty state **READY TO DEV** @mi6-577  @GCHQDeveloper823 
- [x] Footer **READY TO DEV** @GCHQDeveloper618 @GCHQ-Developer-701
- [x] Hero  **READY TO DEV** @GCHQDeveloper618 @GCHQ-Developer-701 
- [x] Link **READY TO DEV** @GCHQ-Developer-465 @mi6-577 
- [x] Loading indicator **READY TO DEV** @GCHQ-Developer-465 @mi6-577 
- [x] Navigation bar  **READY TO DEV** @mi6-577  @GCHQ-Developer-094
- [x] Page header **READY TO DEV** @GCHQ-Developer-465 @GCHQDeveloper823 
- [x] Pagination  **READY TO DEV** @GCHQDeveloper618 added comments 💬 @GCHQ-Developer-701 
- [x] Popover menu **READY TO DEV** @GCHQ-Developer-094 @GCHQDeveloper618 
- [x] Radio button **READY TO DEV** @GCHQ-Developer-465 @GCHQDeveloper618 @GCHQDeveloper823
- [x] Search bar **READY TO DEV** @GCHQ-Developer-465 @GCHQ-Developer-094  
- [x] Select **READY TO DEV**
- [x] Side navigation **READY TO DEV** @mi6-577  @GCHQDeveloper618 
- [x] Skeleton  **READY TO DEV** @mi6-577  @GCHQDeveloper618 @GCHQ-Developer-094
- [x] Status tag - **READY TO DEV** @GCHQ-Developer-701 @mi6-577
- [x] Stepper - **READY TO DEV** @GCHQ-Developer-465  @mi6-577
- [x] Switch **READY TO DEV** @GCHQ-Developer-465 @GCHQDeveloper618 
- [x] Tabs **READY TO DEV** @GCHQ-Developer-701  @GCHQDeveloper823 
- [x] Table of content **READY TO DEV** @GCHQDeveloper618 @mi6-577 
- [x] Text field **READY TO DEV** @mi6-577  @GCHQ-Developer-465 @GCHQ-Developer-701 @GCHQDeveloper823 
- [x] Toast **READY TO DEV** @mi6-577 @GCHQDeveloper618
- [x] Toggle button **READY TO DEV** @GCHQDeveloper823 
- [x] Tooltip **READY TO DEV** @GCHQDeveloper823 @GCHQ-Developer-701 
- [x] Top navigation **READY TO DEV** @GCHQDeveloper618 ✅ @GCHQ-Developer-701 - awaiting further advice
- [x] Tree view **READY TO DEV** @GCHQ-Developer-465 @mi6-577 

## 💰 User value 
Ensure that the naming conventions are correct for Dark Mode work.
