### ISSUE TITLE
Introduce a PR checklist

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#866]
## Summary
Introduce a PR checklist, to allow those suggesting code to check it meets all our criteria and not merge code that is not "done".

## 💬 Description
The following should be introduced:
- A checklist discussed with the team on every PR in both ic-ui-kit and ic-design-system (this may be the definition of done)
- A process to prevent merge if an item is not checked (making optional points clear)

Suggested PR checklist:

- [ ] Relevant unit tests and visual regression tests added. 
- [ ] Visual testing against Figma component specification completed. 
- [ ] All acceptance criteria reviewed and met. 
- [ ] Accessibility Insights FastPass performed.
- [ ] A11y unit test added and yields no issues.
- [ ] A11y plug-in on Storybook yields no issues. 
- [ ] Manual screen reader testing performed using NVDA and VoiceOver. 
- [ ] Page can be zoomed to 400% with no loss of content. 
- [ ] Screen magnifier used with no issues. 
- [ ] Text resized to 200% with no loss of content.
- [ ] Text spacing increased as per the [WCAG 1.4.12 success criterion](https://www.w3.org/TR/WCAG21/#text-spacing) with no loss of content.
- [ ] Browser setting 'prefers reduced motion' tested. No animations or motion visible whilst this setting is on. 
- [ ] Windows High Contrast mode tested with no loss of content.
- [ ] System light and dark mode tested with no loss of content. 
- [ ] Manual keyboard testing for keyboard controls and logical focus order. 
- [ ] Min/max content examples tested with no loss of content or overflow. 
- [ ] Browser support tested (Chrome, Safari, Firefox and Edge).
- [ ] Correct roles used and ARIA attributes used correctly where required. 
- [ ] Logical heading structure is maintained, and the HTML elements used for headings can be changed to fit within the wider page structure. 
- [ ] All prop combinations work without issue. 

## 💰 Use value
Improve product quality and reduce bugs.

**Comment by GCHQ-Developer-847** [comment]
PR created for action to prevent merge if there are uncompleted tasks: https://github.com/mi6/ic-ui-kit/pull/930

**Comment by GCHQ-Developer-847** [comment]
PR created to add checklist to PR template: #1087
